//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Es.Udc.DotNet.MiniPortal.Model", "FK_Comment_User", "UserProfile", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Es.Udc.DotNet.MiniPortal.Model.UserProfile), "Comment", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Es.Udc.DotNet.MiniPortal.Model.Comment), true)]
[assembly: EdmRelationshipAttribute("Es.Udc.DotNet.MiniPortal.Model", "FK_Favourite_User", "UserProfile", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Es.Udc.DotNet.MiniPortal.Model.UserProfile), "Favourite", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Es.Udc.DotNet.MiniPortal.Model.Favourite), true)]
[assembly: EdmRelationshipAttribute("Es.Udc.DotNet.MiniPortal.Model", "FK_Valuation_User", "UserProfile", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Es.Udc.DotNet.MiniPortal.Model.UserProfile), "Valuation", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Es.Udc.DotNet.MiniPortal.Model.Valuation), true)]
[assembly: EdmRelationshipAttribute("Es.Udc.DotNet.MiniPortal.Model", "LabelComment", "Comment", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Es.Udc.DotNet.MiniPortal.Model.Comment), "Label", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Es.Udc.DotNet.MiniPortal.Model.Label))]

#endregion

namespace Es.Udc.DotNet.MiniPortal.Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class MiniPortalEntitiesContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new MiniPortalEntitiesContainer object using the connection string found in the 'MiniPortalEntitiesContainer' section of the application configuration file.
        /// </summary>
        public MiniPortalEntitiesContainer() : base("name=MiniPortalEntitiesContainer", "MiniPortalEntitiesContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MiniPortalEntitiesContainer object.
        /// </summary>
        public MiniPortalEntitiesContainer(string connectionString) : base(connectionString, "MiniPortalEntitiesContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MiniPortalEntitiesContainer object.
        /// </summary>
        public MiniPortalEntitiesContainer(EntityConnection connection) : base(connection, "MiniPortalEntitiesContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Comment> Comment
        {
            get
            {
                if ((_Comment == null))
                {
                    _Comment = base.CreateObjectSet<Comment>("Comment");
                }
                return _Comment;
            }
        }
        private ObjectSet<Comment> _Comment;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Favourite> Favourite
        {
            get
            {
                if ((_Favourite == null))
                {
                    _Favourite = base.CreateObjectSet<Favourite>("Favourite");
                }
                return _Favourite;
            }
        }
        private ObjectSet<Favourite> _Favourite;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Label> Label
        {
            get
            {
                if ((_Label == null))
                {
                    _Label = base.CreateObjectSet<Label>("Label");
                }
                return _Label;
            }
        }
        private ObjectSet<Label> _Label;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<UserProfile> UserProfile
        {
            get
            {
                if ((_UserProfile == null))
                {
                    _UserProfile = base.CreateObjectSet<UserProfile>("UserProfile");
                }
                return _UserProfile;
            }
        }
        private ObjectSet<UserProfile> _UserProfile;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Valuation> Valuation
        {
            get
            {
                if ((_Valuation == null))
                {
                    _Valuation = base.CreateObjectSet<Valuation>("Valuation");
                }
                return _Valuation;
            }
        }
        private ObjectSet<Valuation> _Valuation;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Comment EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToComment(Comment comment)
        {
            base.AddObject("Comment", comment);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Favourite EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFavourite(Favourite favourite)
        {
            base.AddObject("Favourite", favourite);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Label EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLabel(Label label)
        {
            base.AddObject("Label", label);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the UserProfile EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUserProfile(UserProfile userProfile)
        {
            base.AddObject("UserProfile", userProfile);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Valuation EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToValuation(Valuation valuation)
        {
            base.AddObject("Valuation", valuation);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Es.Udc.DotNet.MiniPortal.Model", Name="Comment")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Comment : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Comment object.
        /// </summary>
        /// <param name="commentId">Initial value of the commentId property.</param>
        /// <param name="txt">Initial value of the txt property.</param>
        /// <param name="addDate">Initial value of the addDate property.</param>
        /// <param name="productId">Initial value of the productId property.</param>
        /// <param name="userProfileId">Initial value of the userProfileId property.</param>
        public static Comment CreateComment(global::System.Int64 commentId, global::System.String txt, global::System.DateTime addDate, global::System.Int64 productId, global::System.Int64 userProfileId)
        {
            Comment comment = new Comment();
            comment.commentId = commentId;
            comment.txt = txt;
            comment.addDate = addDate;
            comment.productId = productId;
            comment.userProfileId = userProfileId;
            return comment;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 commentId
        {
            get
            {
                return _commentId;
            }
            set
            {
                if (_commentId != value)
                {
                    OncommentIdChanging(value);
                    ReportPropertyChanging("commentId");
                    _commentId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("commentId");
                    OncommentIdChanged();
                }
            }
        }
        private global::System.Int64 _commentId;
        partial void OncommentIdChanging(global::System.Int64 value);
        partial void OncommentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String txt
        {
            get
            {
                return _txt;
            }
            set
            {
                OntxtChanging(value);
                ReportPropertyChanging("txt");
                _txt = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("txt");
                OntxtChanged();
            }
        }
        private global::System.String _txt;
        partial void OntxtChanging(global::System.String value);
        partial void OntxtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime addDate
        {
            get
            {
                return _addDate;
            }
            set
            {
                OnaddDateChanging(value);
                ReportPropertyChanging("addDate");
                _addDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("addDate");
                OnaddDateChanged();
            }
        }
        private global::System.DateTime _addDate;
        partial void OnaddDateChanging(global::System.DateTime value);
        partial void OnaddDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 productId
        {
            get
            {
                return _productId;
            }
            set
            {
                OnproductIdChanging(value);
                ReportPropertyChanging("productId");
                _productId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("productId");
                OnproductIdChanged();
            }
        }
        private global::System.Int64 _productId;
        partial void OnproductIdChanging(global::System.Int64 value);
        partial void OnproductIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 userProfileId
        {
            get
            {
                return _userProfileId;
            }
            set
            {
                OnuserProfileIdChanging(value);
                ReportPropertyChanging("userProfileId");
                _userProfileId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("userProfileId");
                OnuserProfileIdChanged();
            }
        }
        private global::System.Int64 _userProfileId;
        partial void OnuserProfileIdChanging(global::System.Int64 value);
        partial void OnuserProfileIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Es.Udc.DotNet.MiniPortal.Model", "FK_Comment_User", "UserProfile")]
        public UserProfile UserProfile
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserProfile>("Es.Udc.DotNet.MiniPortal.Model.FK_Comment_User", "UserProfile").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserProfile>("Es.Udc.DotNet.MiniPortal.Model.FK_Comment_User", "UserProfile").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<UserProfile> UserProfileReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserProfile>("Es.Udc.DotNet.MiniPortal.Model.FK_Comment_User", "UserProfile");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<UserProfile>("Es.Udc.DotNet.MiniPortal.Model.FK_Comment_User", "UserProfile", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Es.Udc.DotNet.MiniPortal.Model", "LabelComment", "Label")]
        public EntityCollection<Label> Label
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Label>("Es.Udc.DotNet.MiniPortal.Model.LabelComment", "Label");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Label>("Es.Udc.DotNet.MiniPortal.Model.LabelComment", "Label", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Es.Udc.DotNet.MiniPortal.Model", Name="Favourite")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Favourite : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Favourite object.
        /// </summary>
        /// <param name="favouriteId">Initial value of the favouriteId property.</param>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="addDate">Initial value of the addDate property.</param>
        /// <param name="productId">Initial value of the productId property.</param>
        /// <param name="userProfileId">Initial value of the userProfileId property.</param>
        public static Favourite CreateFavourite(global::System.Int64 favouriteId, global::System.String name, global::System.DateTime addDate, global::System.Int64 productId, global::System.Int64 userProfileId)
        {
            Favourite favourite = new Favourite();
            favourite.favouriteId = favouriteId;
            favourite.name = name;
            favourite.addDate = addDate;
            favourite.productId = productId;
            favourite.userProfileId = userProfileId;
            return favourite;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 favouriteId
        {
            get
            {
                return _favouriteId;
            }
            set
            {
                if (_favouriteId != value)
                {
                    OnfavouriteIdChanging(value);
                    ReportPropertyChanging("favouriteId");
                    _favouriteId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("favouriteId");
                    OnfavouriteIdChanged();
                }
            }
        }
        private global::System.Int64 _favouriteId;
        partial void OnfavouriteIdChanging(global::System.Int64 value);
        partial void OnfavouriteIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String comment
        {
            get
            {
                return _comment;
            }
            set
            {
                OncommentChanging(value);
                ReportPropertyChanging("comment");
                _comment = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("comment");
                OncommentChanged();
            }
        }
        private global::System.String _comment;
        partial void OncommentChanging(global::System.String value);
        partial void OncommentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime addDate
        {
            get
            {
                return _addDate;
            }
            set
            {
                OnaddDateChanging(value);
                ReportPropertyChanging("addDate");
                _addDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("addDate");
                OnaddDateChanged();
            }
        }
        private global::System.DateTime _addDate;
        partial void OnaddDateChanging(global::System.DateTime value);
        partial void OnaddDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 productId
        {
            get
            {
                return _productId;
            }
            set
            {
                OnproductIdChanging(value);
                ReportPropertyChanging("productId");
                _productId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("productId");
                OnproductIdChanged();
            }
        }
        private global::System.Int64 _productId;
        partial void OnproductIdChanging(global::System.Int64 value);
        partial void OnproductIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 userProfileId
        {
            get
            {
                return _userProfileId;
            }
            set
            {
                OnuserProfileIdChanging(value);
                ReportPropertyChanging("userProfileId");
                _userProfileId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("userProfileId");
                OnuserProfileIdChanged();
            }
        }
        private global::System.Int64 _userProfileId;
        partial void OnuserProfileIdChanging(global::System.Int64 value);
        partial void OnuserProfileIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Es.Udc.DotNet.MiniPortal.Model", "FK_Favourite_User", "UserProfile")]
        public UserProfile UserProfile
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserProfile>("Es.Udc.DotNet.MiniPortal.Model.FK_Favourite_User", "UserProfile").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserProfile>("Es.Udc.DotNet.MiniPortal.Model.FK_Favourite_User", "UserProfile").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<UserProfile> UserProfileReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserProfile>("Es.Udc.DotNet.MiniPortal.Model.FK_Favourite_User", "UserProfile");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<UserProfile>("Es.Udc.DotNet.MiniPortal.Model.FK_Favourite_User", "UserProfile", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Es.Udc.DotNet.MiniPortal.Model", Name="Label")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Label : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Label object.
        /// </summary>
        /// <param name="labelId">Initial value of the labelId property.</param>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="cnt">Initial value of the cnt property.</param>
        public static Label CreateLabel(global::System.Int64 labelId, global::System.String name, global::System.Int64 cnt)
        {
            Label label = new Label();
            label.labelId = labelId;
            label.name = name;
            label.cnt = cnt;
            return label;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 labelId
        {
            get
            {
                return _labelId;
            }
            set
            {
                if (_labelId != value)
                {
                    OnlabelIdChanging(value);
                    ReportPropertyChanging("labelId");
                    _labelId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("labelId");
                    OnlabelIdChanged();
                }
            }
        }
        private global::System.Int64 _labelId;
        partial void OnlabelIdChanging(global::System.Int64 value);
        partial void OnlabelIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 cnt
        {
            get
            {
                return _cnt;
            }
            set
            {
                OncntChanging(value);
                ReportPropertyChanging("cnt");
                _cnt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cnt");
                OncntChanged();
            }
        }
        private global::System.Int64 _cnt;
        partial void OncntChanging(global::System.Int64 value);
        partial void OncntChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Es.Udc.DotNet.MiniPortal.Model", "LabelComment", "Comment")]
        public EntityCollection<Comment> Comment
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Comment>("Es.Udc.DotNet.MiniPortal.Model.LabelComment", "Comment");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Comment>("Es.Udc.DotNet.MiniPortal.Model.LabelComment", "Comment", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Es.Udc.DotNet.MiniPortal.Model", Name="UserProfile")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UserProfile : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new UserProfile object.
        /// </summary>
        /// <param name="usrId">Initial value of the usrId property.</param>
        /// <param name="loginName">Initial value of the loginName property.</param>
        /// <param name="enPassword">Initial value of the enPassword property.</param>
        /// <param name="firstName">Initial value of the firstName property.</param>
        /// <param name="lastName">Initial value of the lastName property.</param>
        /// <param name="email">Initial value of the email property.</param>
        public static UserProfile CreateUserProfile(global::System.Int64 usrId, global::System.String loginName, global::System.String enPassword, global::System.String firstName, global::System.String lastName, global::System.String email)
        {
            UserProfile userProfile = new UserProfile();
            userProfile.usrId = usrId;
            userProfile.loginName = loginName;
            userProfile.enPassword = enPassword;
            userProfile.firstName = firstName;
            userProfile.lastName = lastName;
            userProfile.email = email;
            return userProfile;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 usrId
        {
            get
            {
                return _usrId;
            }
            set
            {
                if (_usrId != value)
                {
                    OnusrIdChanging(value);
                    ReportPropertyChanging("usrId");
                    _usrId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("usrId");
                    OnusrIdChanged();
                }
            }
        }
        private global::System.Int64 _usrId;
        partial void OnusrIdChanging(global::System.Int64 value);
        partial void OnusrIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String loginName
        {
            get
            {
                return _loginName;
            }
            set
            {
                OnloginNameChanging(value);
                ReportPropertyChanging("loginName");
                _loginName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("loginName");
                OnloginNameChanged();
            }
        }
        private global::System.String _loginName;
        partial void OnloginNameChanging(global::System.String value);
        partial void OnloginNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String enPassword
        {
            get
            {
                return _enPassword;
            }
            set
            {
                OnenPasswordChanging(value);
                ReportPropertyChanging("enPassword");
                _enPassword = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("enPassword");
                OnenPasswordChanged();
            }
        }
        private global::System.String _enPassword;
        partial void OnenPasswordChanging(global::System.String value);
        partial void OnenPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String firstName
        {
            get
            {
                return _firstName;
            }
            set
            {
                OnfirstNameChanging(value);
                ReportPropertyChanging("firstName");
                _firstName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("firstName");
                OnfirstNameChanged();
            }
        }
        private global::System.String _firstName;
        partial void OnfirstNameChanging(global::System.String value);
        partial void OnfirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String lastName
        {
            get
            {
                return _lastName;
            }
            set
            {
                OnlastNameChanging(value);
                ReportPropertyChanging("lastName");
                _lastName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("lastName");
                OnlastNameChanged();
            }
        }
        private global::System.String _lastName;
        partial void OnlastNameChanging(global::System.String value);
        partial void OnlastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Es.Udc.DotNet.MiniPortal.Model", "FK_Comment_User", "Comment")]
        public EntityCollection<Comment> Comment
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Comment>("Es.Udc.DotNet.MiniPortal.Model.FK_Comment_User", "Comment");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Comment>("Es.Udc.DotNet.MiniPortal.Model.FK_Comment_User", "Comment", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Es.Udc.DotNet.MiniPortal.Model", "FK_Favourite_User", "Favourite")]
        public EntityCollection<Favourite> Favourite
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Favourite>("Es.Udc.DotNet.MiniPortal.Model.FK_Favourite_User", "Favourite");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Favourite>("Es.Udc.DotNet.MiniPortal.Model.FK_Favourite_User", "Favourite", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Es.Udc.DotNet.MiniPortal.Model", "FK_Valuation_User", "Valuation")]
        public EntityCollection<Valuation> Valuation
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Valuation>("Es.Udc.DotNet.MiniPortal.Model.FK_Valuation_User", "Valuation");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Valuation>("Es.Udc.DotNet.MiniPortal.Model.FK_Valuation_User", "Valuation", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Es.Udc.DotNet.MiniPortal.Model", Name="Valuation")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Valuation : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Valuation object.
        /// </summary>
        /// <param name="valuationId">Initial value of the valuationId property.</param>
        /// <param name="score">Initial value of the score property.</param>
        /// <param name="addDate">Initial value of the addDate property.</param>
        /// <param name="sellerId">Initial value of the sellerId property.</param>
        /// <param name="userProfileId">Initial value of the userProfileId property.</param>
        /// <param name="productId">Initial value of the productId property.</param>
        public static Valuation CreateValuation(global::System.Int64 valuationId, global::System.Int64 score, global::System.DateTime addDate, global::System.String sellerId, global::System.Int64 userProfileId, global::System.Int64 productId)
        {
            Valuation valuation = new Valuation();
            valuation.valuationId = valuationId;
            valuation.score = score;
            valuation.addDate = addDate;
            valuation.sellerId = sellerId;
            valuation.userProfileId = userProfileId;
            valuation.productId = productId;
            return valuation;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 valuationId
        {
            get
            {
                return _valuationId;
            }
            set
            {
                if (_valuationId != value)
                {
                    OnvaluationIdChanging(value);
                    ReportPropertyChanging("valuationId");
                    _valuationId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("valuationId");
                    OnvaluationIdChanged();
                }
            }
        }
        private global::System.Int64 _valuationId;
        partial void OnvaluationIdChanging(global::System.Int64 value);
        partial void OnvaluationIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 score
        {
            get
            {
                return _score;
            }
            set
            {
                OnscoreChanging(value);
                ReportPropertyChanging("score");
                _score = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("score");
                OnscoreChanged();
            }
        }
        private global::System.Int64 _score;
        partial void OnscoreChanging(global::System.Int64 value);
        partial void OnscoreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime addDate
        {
            get
            {
                return _addDate;
            }
            set
            {
                OnaddDateChanging(value);
                ReportPropertyChanging("addDate");
                _addDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("addDate");
                OnaddDateChanged();
            }
        }
        private global::System.DateTime _addDate;
        partial void OnaddDateChanging(global::System.DateTime value);
        partial void OnaddDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String txt
        {
            get
            {
                return _txt;
            }
            set
            {
                OntxtChanging(value);
                ReportPropertyChanging("txt");
                _txt = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("txt");
                OntxtChanged();
            }
        }
        private global::System.String _txt;
        partial void OntxtChanging(global::System.String value);
        partial void OntxtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String sellerId
        {
            get
            {
                return _sellerId;
            }
            set
            {
                OnsellerIdChanging(value);
                ReportPropertyChanging("sellerId");
                _sellerId = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("sellerId");
                OnsellerIdChanged();
            }
        }
        private global::System.String _sellerId;
        partial void OnsellerIdChanging(global::System.String value);
        partial void OnsellerIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 userProfileId
        {
            get
            {
                return _userProfileId;
            }
            set
            {
                OnuserProfileIdChanging(value);
                ReportPropertyChanging("userProfileId");
                _userProfileId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("userProfileId");
                OnuserProfileIdChanged();
            }
        }
        private global::System.Int64 _userProfileId;
        partial void OnuserProfileIdChanging(global::System.Int64 value);
        partial void OnuserProfileIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 productId
        {
            get
            {
                return _productId;
            }
            set
            {
                OnproductIdChanging(value);
                ReportPropertyChanging("productId");
                _productId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("productId");
                OnproductIdChanged();
            }
        }
        private global::System.Int64 _productId;
        partial void OnproductIdChanging(global::System.Int64 value);
        partial void OnproductIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Es.Udc.DotNet.MiniPortal.Model", "FK_Valuation_User", "UserProfile")]
        public UserProfile UserProfile
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserProfile>("Es.Udc.DotNet.MiniPortal.Model.FK_Valuation_User", "UserProfile").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserProfile>("Es.Udc.DotNet.MiniPortal.Model.FK_Valuation_User", "UserProfile").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<UserProfile> UserProfileReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserProfile>("Es.Udc.DotNet.MiniPortal.Model.FK_Valuation_User", "UserProfile");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<UserProfile>("Es.Udc.DotNet.MiniPortal.Model.FK_Valuation_User", "UserProfile", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
